method: grid
name: 4M_bothrndm_onlyvarianceis5seeds
metric:
  name: improvement_score   # <-- optimize improvement, not final SR
  goal: maximize
parameters:
  learning_rate:
    values: [3e-4]
  ent_coef:
    values: [0.02]
  batch_size:
    values: [256]
  clip_range:
    values: [0.03]
  seed:
    values: [0, 7, 11, 31, 42]
